version: '3.9'

services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"]
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"]
      interval: 10s

  marques-ms:
    build: ./marque-microservice
    container_name: marques-ms
    ports:
      - "8090:8090"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8090/actuator/health | grep UP || exit 1"]
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  marques-ms2:
    build: ./marque-microservice
    container_name: marques-ms2
    ports:
      - "8094:8090"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8094/actuator/health | grep UP || exit 1"]
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
    depends_on:
      eurekaserver:
        condition: service_healthy

  pcs-ms:
    build: ./pc-microservice
    container_name: pcs-ms
    ports:
      - "8081:8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      marques-ms:
        condition: service_healthy
