version: '3.9'

services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"]
      interval: 10s
    networks:
      - spring-net

  configserver:
    build: ./configserver
    container_name: configserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"]
      interval: 10s
    networks:
      - spring-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8092:8080"
    networks:
      - spring-net

  marques-ms:
    build: ./marque-microservice
    container_name: marques-ms
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - spring-net

  marques-ms2:
    build: ./marque-microservice
    container_name: marques-ms2
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - spring-net

  pcs-ms:
    build: ./pc-microservice
    container_name: pcs-ms
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      marques-ms:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - spring-net

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
    depends_on:
      eurekaserver:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
